### ISSUE TITLE
How can I download custom dlc quest on 3ds Japan import?

### ISSUE THREAD

**Issue by Humankimchi** [svanheulen/mhqs#1]
I want to download custom dlc quest on my japanese 3ds.
I runed mh4u_proxy.py and connected download contents, but my japanese 3ds can't connect download menu cause error code  090-2442.
Is it impossible?

**Comment by svanheulen** [comment]
Sorry, it currently only works with the USA and EUR versions of the game.
If you can use NINJHAX, I can walk you through the process of getting the encryption key from the Japanese game and then I can make it work for you.

**Comment by Humankimchi** [comment]
Thank you to answer. Sadly I have no 9.2 ver. 3DS.
