### ISSUE TITLE
How can I get blowfish crypto key with running NTR-CFW 3DS?

### ISSUE THREAD

**Issue by Humankimchi** [svanheulen/mhqs#3]
Hello, svanheulen!
My friend's 3DS can run NTR-CFW. Could you tell me how to get encryption key? Um... detailedly?

**Comment by svanheulen** [comment]
It would be best if you could talk to me on freenode. I'm in the eastern timezone though so if that doesn't work, just give me a bit to write up a good walkthrough.

**Comment by Humankimchi** [comment]
This problem was solved. but I have another problem...
When I edit Quest Boss, then I can't order that Quest in game. I can edit other things without boss offset(maybe all monster offset?). Do you know why this problem happened?

**Comment by svanheulen** [comment]
Not sure yet, people are looking into it but I don't think anyone has figured it out yet.

**Comment by aesth0x** [comment]
Hi, what's your game region? would you like to share the encryption key? Thanks!

**Comment by svanheulen** [comment]
I just checked and my copy of the Japanese game should arrive in about 3 days. So I'll get the key soon :)

**Comment by Humankimchi** [comment]
I have updated MH4G JP encryption key.
